# Generated by Django 5.1.2 on 2024-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
